config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: %i[show index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  resources :posts, except: :new do
    resources :comments, except: :new
  end
  post 'posts/:post_id/comments/:id', to: 'comments#create'
  post 'posts/:id', to: 'comments#create'
  get 'users', to: 'posts#index'
  root 'posts#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :comments, as: :has_comment, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def comments
    Comment.where(user_id: id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  #
  #   def create
  #     build_resource(sign_up_params)
  #
  #     resource.save
  #     yield resource if block_given?
  #     if resource.persisted?
  #       if resource.active_for_authentication?
  #         set_flash_message! :notice, :signed_up
  #         sign_up(resource_name, resource)
  #         respond_with resource, location: after_sign_up_path_for(resource)
  #       else
  #         set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
  #         expire_data_after_sign_in!
  #         respond_with resource, location: after_inactive_sign_up_path_for(resource)
  #       end
  #     else
  #       clean_up_passwords resource
  #       set_minimum_password_length
  #       render action: 'new', status: :unprocessable_entity
  #     end
  #   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def after_sign_up_path_for(_resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #  super
  # end

  #
  # def new
  #     self.resource = resource_class.new(sign_in_params)
  #     clean_up_passwords(resource)
  #     yield resource if block_given?
  #     respond_with(resource, serialize_options(resource))
  #   end

  # POST /resource/sign_in
  # def sign_in
  #  super
  # end

  #
  #   def create
  #     self.resource = warden.authenticate!(auth_options)
  #     set_flash_message!(:notice, :signed_in)
  #     sign_in(resource_name, resource)
  #     yield resource if block_given?
  #     respond_with resource, location: after_sign_in_path_for(resource)
  #   end

  # POST /resource/sign_in
  #    def create
  #     self.resource = warden.authenticate!(auth_options)
  #
  #     if resource
  #       set_flash_message!(:notice, :signed_in)
  #       sign_in(resource_name, resource)
  #       yield resource if block_given?
  #       respond_with resource, location: after_sign_in_path_for(resource)
  #     else
  #       self.resource = resource_class.new(sign_in_params)
  #       clean_up_passwords(resource)
  #       set_flash_message!(:alert, :invalid)
  #       # flash.now[:alert] = 'Invalid email or password.'
  #       render action: 'new', status: :unprocessable_entity
  #     end
  #   end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  # def after_sign_in_path_for(_resource)
  #  root_path
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_inline_errors.html.erb
<% unless errors.empty? %>
  <div id="error_explanation" class='bg-red-300 mt-2 rounded-md p-2'>
    <%= errors.join(', ').capitalize %>.
  </div>
<% end %>

app/views/users/_user.html.erb
<% if user_signed_in? %>
  <div class="">
    <%= link_to user.username, user_path(user) %>
  </div>
<% else %>
  <div class="">????</div>
<% end%>

app/views/users/_user_profile.html.erb
<div class="max-w-4xl flex items-center py-8 sm:py-20 flex-wrap mx-auto sm:my-32 lg:my-0">
  <!--Main Col-->
  <div id="profile" class="w-full lg:w-3/5 rounded-lg lg:rounded-l-lg shadow-2xl bg-white mx-6 lg:mx-0">
    <div class="p-4 md:p-12 text-center lg:text-left">
      <!-- Image for mobile view-->
      <div class="block lg:hidden rounded-full shadow-xl mx-auto -mt-16 h-48 w-48 bg-cover bg-center" style="background-image: url(https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png')"></div>
      <h1 class="text-3xl font-bold pt-8 lg:pt-0"><%= @user.name.capitalize %></h1>
      <div class="mx-auto lg:mx-0 w-4/5 pt-3 border-b-2 border-green-500 opacity-25"></div>
      <p class="pt-4 text-base font-bold flex items-center justify-center lg:justify-start">
        <svg class="h-4 fill-current text-green-700 pr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9 12H1v6a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-6h-8v2H9v-2zm0-1H0V5c0-1.1.9-2 2-2h4V2a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v1h4a2 2 0 0 1 2 2v6h-9V9H9v2zm3-8V2H8v1h4z"/></svg>
        <%= @user.username %>
      </p>
      <p class="pt-2 flex flex-row items-center justify-center lg:justify-start text-xs lg:text-sm text-gray-600">
        <svg class='h-4 fill-current text-green-700 pr-4' xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" viewBox="0 0 512 512"><path d="M491,107a6,6,0,0,0-6-6H27a6,6,0,0,0-6,6V405a6,6,0,0,0,6,6H485a6,6,0,0,0,6-6ZM256,313.185,41.751,113H470.218Zm-79.508-57.657L33,390.622V121.455Zm8.792,8.311,66.62,62.2A6.019,6.019,0,0,0,260.1,326l69.146-64.522L470.474,399H41.829Zm152.743-10.675L479,121.426V390.343Z"></path></svg>
        <%= @user.email %>
      </p>
      <p class="pt-8 text-sm">Totally optional short description about yourself, what you do and so on.</p>
      <div class="pt-12 pb-8">
        <%= button_to 'Follow', root_path, class: 'bg-green-700 hover:bg-green-900 text-white font-bold py-2 px-4 rounded-full' %>
      </div>
      <div class="mt-6 pb-16 lg:pb-0 w-4/5 lg:w-full mx-auto flex flex-wrap items-center justify-between">
        social media links here
      </div>
    </div>
  </div>
  <div class="w-full lg:w-2/5">
    <img src="https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png" class="rounded-none lg:rounded-r-lg shadow-2xl hidden lg:block">
  </div>
</div>

app/views/users/index.html.erb
<h1 class="text-9xl">Users</h1>

app/views/users/show.html.erb
<div class="bg-blue-400 w-full max-w-screen-lg">
  <%= render 'user_profile', user: @user %>
  <div class="bg-white mx-5 sm:mx-10 rounded-md p-6 sm:p-2 sm:py-8 shadow-2xl mb-4 sm:mb-16">
    <div class="bg-white text-3xl font-bold sm:px-6 py-2 rounded-md">Posts by <%= @user.username %></div>
    <%= render @user.posts, links: true, parent: true %>
  </div>
  <div class="bg-white mx-5 sm:mx-10 rounded-md p-6 sm:p-2 sm:py-8 shadow-2xl mb-4 sm:mb-16">
    <div class="bg-white text-3xl font-bold sm:px-6 py-2 rounded-md">Comments by <%= @user.username %></div>
    <%= render @user.comments, links: true, parent: true %>
  </div>
</div>