config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, only: %i[show index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  resources :posts, except: :new do
    resources :comments, except: :new
  end
  post 'posts/:post_id/comments/:id', to: 'comments#create'
  post 'posts/:id', to: 'comments#create'
  get 'users', to: 'posts#index'
  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, as: :parent, dependent: :destroy

  validates :body, presence: true

  def post_id
    id
  end

  def path_parent
    self
  end

  def path_self
    self
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[destroy edit show update]
  before_action :authenticate_user!, except: %i[index show]
  before_action :create_comment, only: :show
  def index
    @posts = Post.includes(:comments, :user).all

    @post = Post.new
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post edited succesfully!'
    else
      render action: 'edit', status: :unprocessable_entity
    end
  end

  def show; end

  def destroy
    @post.destroy
    redirect_to root_path, notice: 'Post was succesfully deleted.'
  end

  def create
    @posts = Post.includes(:comments, :user).all
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: 'Post created succesfully!'
    else
      render action: 'index', status: :unprocessable_entity
    end
  end

  private

  def find_post
    @post = Post.includes(:user, :comments).find(params[:id])
  end

  def post_params
    params.require(:post).permit(:body)
  end

  def create_comment
    return unless user_signed_in?

    @new_comment = @post.comments.build(post_id: @post.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_banner_ad.html.erb
<div class="w-full max-w-xs sticky [height:fit-content] [top:72px] hidden lg:block">
  <img src="https://www.deminimis.com.au/uploads/2/7/6/0/27609311/local-singles_orig.jpg" alt="" class='pt-20'>
  <img src="https://www.deminimis.com.au/uploads/2/7/6/0/27609311/local-singles_orig.jpg" alt="" class='pt-20'>
  <img src="https://www.deminimis.com.au/uploads/2/7/6/0/27609311/local-singles_orig.jpg" alt="" class='pt-20 hidden 2xl:block'>
</div>

app/views/posts/_edit.html.erb
<%= form_with model:resource, url: resource.path_self, class: 'w-full h-full flex flex-col' do |form| %>
  <%= form.text_area :body, placeholder: 'Start a post...', rows: 5, autofocus: true, class: 'border-none w-full rounded-md h-full resize-none' %>
  <%= render "users/inline_errors", errors: resource.errors.full_messages %>
  <%= form.submit 'Submit', class: 'self-end bg-white p-2 mt-2 rounded-md border-2 border-transparent hover:border-2 hover:border-black w-fit' %>
<% end %>

app/views/posts/_post.html.erb
<div class='bg-white p-4 lg:p-6 lg:mx-10 sm:my-5 border-b-2 border-blue-400 sm:border-none lg:rounded-lg shadow-2xl'>
  <div class="flex flex-row">
    <%= render post.user %>
    <div class="ml-auto">posted: <%= post.created_at.strftime('%H:%M:%S %d-%m-%y') %></div>
  </div>
  <div class="flex flex-col">
    <div class="p-6 bg-blue-100 lg:rounded-md my-2"><%= post.body %></div>
    <% if local_assigns[:links] %>
      <div class="flex flex-row justify-between ml-2">
        <ul class="flex flex-row w-full align-middle text-sm">
          <li class="w-fit underline">
            <%= button_to (post.comments_count || 0).to_s + ' comments', post, method: :get, class: 'underline text-sm' %>
          </li>
          <li class=" ml-2"><%= button_to 'view', post, method: :get %></li>
          <li class=" ml-2"><%= button_to 'share', post, method: :get %></li>
          <% if user_signed_in? %>
            <li class=" ml-2"><%= button_to 'reply', post, method: :get %></li>
          <% end %>
          <% if user_signed_in? && current_user.id == post.user_id %>
            <li class=" ml-2"><%= button_to 'edit', edit_post_url(post), method: :get %></li>
            <li class=" ml-2"><%= button_to 'delete', post, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_submit.html.erb
<div class="bg-green-200 p-5 mt-8 border-b-2 border-green-400 sm:border-none sm:mx-10 sm:my-5 sm:rounded-lg min-h-fit sm:shadow-2xl">
  <%= form_with model: @post, class: 'w-full h-full flex flex-col' do |form| %>
    <%= form.text_area :body, placeholder: 'Start a post...', rows: 5, autofocus: true, class: 'border-none w-full rounded-md h-full resize-none' %>
    <%= render "devise/shared/error_messages", resource: @post %>
    <%= form.submit 'Submit', class: 'self-end bg-white p-2 mt-2 rounded-md border-2 border-transparent hover:border-2 hover:border-black w-fit' %>
  <% end %>
</div>

app/views/posts/_submit_new_user.html.erb
<div class="bg-green-200 p-5 sm:mx-10 sm:my-5 sm:rounded-lg min-h-fit shadow-2xl">
  <div class="flex flex-col bg-white rounded-lg p-6 items-center text-center">
    <div class="text-xl">Want to add to the discussion?</div>
    <div class="text-md">Make a Post!</div>
    <div class="text-md">Post a comment!</div>
    <div class="bg-blue-200 p-2 rounded-lg border-2 border-transparent hover:border-blue-400 my-2"><%= link_to 'Create an Account', new_user_registration_path %></div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="bg-gray-200 flex flex-column w-full flex-1 justify-evenly">
  <div class="bg-green-800 w-full max-w-xs">
  </div>
  <div class='bg-blue-400 flex-1 w-full max-w-screen-lg'>
    <%= render 'submit' %>
  </div>
  <div class="bg-green-800 w-full max-w-xs">
  </div>
</div>

app/views/posts/index.html.erb
<%= content_for :col_left do %>
  <%= render 'banner_ad' unless user_signed_in? %>
<% end %>
<div class='bg-blue-400 w-full max-w-screen-lg min-w-md min-h-screen'>
  <%= render 'submit', resource: @post if user_signed_in? %>
  <%= render partial: 'post', collection: @posts, as: :post, locals: { links: true } %>
  <%= render 'submit_new_user' if @posts.empty? %>
</div>
<%= content_for :col_right do %>
  <%= render 'banner_ad' unless user_signed_in? %>
<% end %>

app/views/posts/show.html.erb
<%= content_for :col_left do %>
  <%= render 'banner_ad' unless user_signed_in? %>
<% end %>
<div class='bg-blue-400 w-full max-w-screen-lg min-h-screen'>
  <%= render @post %>
  <%= render 'comments/submit', resource: @new_comment if user_signed_in? %>
  <%= render 'submit_new_user'  unless user_signed_in? %>
  <% if @post.comments.empty? %>
    <%= render 'comments/no_comments' %>
  <% else%>
    <%= render @post.comments.filter {|c| !c.created_at.nil?}, links: true, children: true, parent: true %>
  <% end %>
</div>
<%= content_for :col_right do %>
  <%= render 'banner_ad' unless user_signed_in? %>
<% end %>